=== Ajuan08/AntonioJuanRiosFdez_EXUD4-LMSGI/Ejercicio 1/sucursal.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation xml:lang="Es-es">
            <fecha>14-02-2022</fecha>
            <autor>Antonio Juan</autor>
            <observaciones></observaciones>
        </xs:documentation>
    </xs:annotation>
    <xs:element name="pedidos" type="pedidoDatos" />
    <xs:complexType name="pedidoDatos">
        <xs:sequence>
            <xs:element name="sucursal" type="sucursalDatos" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="sucursalDatos">
        <xs:sequence>
            <xs:element name="nombre_trabajador" type="xs:string" />
            <xs:element name="fecha" type="xs:date" />
            <xs:element name="observacion" type="xs:string" minOccurs="0" />
            <xs:element name="articulo" type="articuloDatos" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="codigo" type="codigoTipo" use="required" />
    </xs:complexType>
    <xs:simpleType name="codigoTipo">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{1}([A-Za-z0-9]){7}" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="articuloDatos">
        <xs:sequence>
            <xs:element name="num_unidades">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:minInclusive value="1" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="precio">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="1" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="observaciones" type="xs:string" />
            <xs:element name="plazo_revision">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:minInclusive value="1" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="codigo" type="codigoArticulo" use="required" />
    </xs:complexType>
    <xs:simpleType name="codigoArticulo">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3}-[0-9]{3}" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Ajuan08/AntonioJuanRiosFdez_EXUD4-LMSGI/Ejercicio 1/sucursal1.xml
<?xml version="1.0" encoding="UTF-8"?>
<pedidos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="sucursal.xsd">
    <sucursal codigo="A1234567">
        <nombre_trabajador>Juan</nombre_trabajador>
        <fecha>2022-02-14</fecha>
        <observacion>Urgente</observacion>
            <articulo codigo="ASD-242">
                <num_unidades>2</num_unidades>
                <precio>20</precio>
                <observaciones>Muy buen estado</observaciones>
                <plazo_revision>15</plazo_revision>
            </articulo>
    </sucursal>
</pedidos>
