=== Ajuan08/AntonioJuanRiosFdez_EXUD4-LMSGI/Ejercicio 1/sucursal.dtd
<!ELEMENT pedidos (sucursal)>
<!ELEMENT sucursal (nombre_trabajador,fecha,observacion,articulo)>
<!ATTLIST sucursal codigo NMTOKEN #REQUIRED>
<!ELEMENT nombre_trabajador (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT observacion (#PCDATA)>
<!ELEMENT articulo (num_unidades,precio,observaciones,plazo_revision)>
<!ATTLIST articulo codigo NMTOKEN #REQUIRED>
<!ELEMENT num_unidades (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT plazo_revision (#PCDATA)>

=== Ajuan08/AntonioJuanRiosFdez_EXUD4-LMSGI/Ejercicio 1/sucursal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos SYSTEM "sucursal.dtd">
<pedidos>
    <sucursal codigo="A1234567">
        <nombre_trabajador>Juan</nombre_trabajador>
        <fecha>2022-02-14</fecha>
        <observacion>Urgente</observacion>
        <articulo codigo="ASD-242">
            <num_unidades>2</num_unidades>
            <precio>20</precio>
            <observaciones>Muy buen estado</observaciones>
            <plazo_revision>15</plazo_revision>
        </articulo>
    </sucursal>
</pedidos>
